from __future__ import annotations

from typing import Any


def _field(
    key: str,
    label: str,
    field_type: str,
    *,
    required: bool = False,
    placeholder: str | None = None,
    default: Any = None,
) -> dict[str, Any]:
    return {
        "key": key,
        "label": label,
        "type": field_type,
        "required": required,
        "placeholder": placeholder,
        "default": default,
    }


CONNECTOR_CATALOG: list[dict[str, Any]] = [
    {
        "connector_key": "mysql",
        "category": "关系型数据库",
        "display_name": "MySQL",
        "runtime_family": "sql-relational",
        "status": "ACTIVE",
        "description": "面向业务库、离线快照库和传统应用数据库的接入。",
        "auth_modes": ["USERNAME_PASSWORD"],
        "capabilities": [
            "connectivity",
            "instance_discovery",
            "asset_discovery",
            "schema_introspection",
            "sample_read",
            "stats_capture",
            "change_watch",
        ],
        "config_schema": [
            _field("host", "主机", "text", required=True, placeholder="127.0.0.1"),
            _field("port", "端口", "number", required=True, default=3306),
            _field("database", "默认数据库", "text"),
            _field("username", "用户名", "text", required=True),
            _field("password", "密码", "password", required=True),
            _field("memory_scope_default", "默认记忆范围", "select", default="PRIVATE"),
        ],
    },
    {
        "connector_key": "postgresql",
        "category": "关系型数据库",
        "display_name": "PostgreSQL",
        "runtime_family": "sql-relational",
        "status": "ACTIVE",
        "description": "通用关系型数据库与分析型数据库接入。",
        "auth_modes": ["USERNAME_PASSWORD"],
        "capabilities": [
            "connectivity",
            "instance_discovery",
            "asset_discovery",
            "schema_introspection",
            "sample_read",
            "stats_capture",
            "change_watch",
        ],
        "config_schema": [
            _field("host", "主机", "text", required=True, placeholder="127.0.0.1"),
            _field("port", "端口", "number", required=True, default=5432),
            _field("database", "默认数据库", "text", required=True),
            _field("schema", "默认 Schema", "text", default="public"),
            _field("username", "用户名", "text", required=True),
            _field("password", "密码", "password", required=True),
            _field("memory_scope_default", "默认记忆范围", "select", default="PRIVATE"),
        ],
    },
    {
        "connector_key": "sqlite",
        "category": "关系型数据库",
        "display_name": "SQLite",
        "runtime_family": "sql-relational",
        "status": "ACTIVE",
        "description": "适合本地样本、嵌入式数据库和测试数据源。",
        "auth_modes": ["FILE_PATH"],
        "capabilities": [
            "connectivity",
            "asset_discovery",
            "schema_introspection",
            "sample_read",
            "stats_capture",
        ],
        "config_schema": [
            _field("file_path", "文件路径", "text", required=True),
            _field("namespace", "命名空间", "text", default="main"),
            _field("memory_scope_default", "默认记忆范围", "select", default="PRIVATE"),
        ],
    },
    {
        "connector_key": "sqlserver",
        "category": "关系型数据库",
        "display_name": "SQL Server",
        "runtime_family": "sql-relational",
        "status": "CATALOG",
        "description": "微软 SQL Server 实例。",
        "auth_modes": ["USERNAME_PASSWORD", "INTEGRATED"],
        "capabilities": ["connectivity", "instance_discovery", "asset_discovery", "schema_introspection", "stats_capture"],
        "config_schema": [
            _field("host", "主机", "text"),
            _field("port", "端口", "number", default=1433),
        ],
    },
    {
        "connector_key": "clickhouse",
        "category": "数仓与查询引擎",
        "display_name": "ClickHouse",
        "runtime_family": "warehouse-sql",
        "status": "CATALOG",
        "description": "列式分析引擎与热点宽表仓。",
        "auth_modes": ["USERNAME_PASSWORD"],
        "capabilities": ["connectivity", "asset_discovery", "schema_introspection", "stats_capture", "query_pushdown"],
        "config_schema": [
            _field("host", "主机", "text"),
            _field("port", "端口", "number", default=8123),
        ],
    },
    {
        "connector_key": "trino",
        "category": "数仓与查询引擎",
        "display_name": "Trino / Presto",
        "runtime_family": "warehouse-sql",
        "status": "CATALOG",
        "description": "联邦查询入口。",
        "auth_modes": ["USERNAME_PASSWORD", "TOKEN"],
        "capabilities": ["connectivity", "asset_discovery", "schema_introspection", "query_pushdown"],
        "config_schema": [
            _field("host", "主机", "text"),
            _field("port", "端口", "number", default=8080),
        ],
    },
    {
        "connector_key": "snowflake",
        "category": "数仓与查询引擎",
        "display_name": "Snowflake",
        "runtime_family": "warehouse-sql",
        "status": "CATALOG",
        "description": "云数仓账户接入。",
        "auth_modes": ["USERNAME_PASSWORD", "KEY_PAIR"],
        "capabilities": ["connectivity", "asset_discovery", "schema_introspection", "stats_capture", "query_pushdown"],
        "config_schema": [
            _field("account", "账户", "text"),
            _field("warehouse", "计算仓", "text"),
        ],
    },
    {
        "connector_key": "s3",
        "category": "对象存储与文件",
        "display_name": "Amazon S3 / MinIO",
        "runtime_family": "object-storage",
        "status": "ACTIVE",
        "description": "对象存储 Bucket 与 Lakehouse 文件目录。",
        "auth_modes": ["ACCESS_KEY"],
        "capabilities": ["connectivity", "asset_discovery", "sample_read", "stats_capture", "change_watch", "snapshot_extract"],
        "config_schema": [
            _field("endpoint_url", "Endpoint", "text", placeholder="http://127.0.0.1:9000"),
            _field("region_name", "Region", "text", default="us-east-1"),
            _field("access_key_id", "Access Key", "text", required=True),
            _field("secret_access_key", "Secret Key", "password", required=True),
            _field("bucket", "Bucket", "text"),
            _field("prefix", "Prefix", "text"),
        ],
    },
    {
        "connector_key": "oss",
        "category": "对象存储与文件",
        "display_name": "阿里云 OSS",
        "runtime_family": "object-storage",
        "status": "CATALOG",
        "description": "对象存储 bucket 与文件目录。",
        "auth_modes": ["ACCESS_KEY"],
        "capabilities": ["connectivity", "asset_discovery", "sample_read", "stats_capture", "change_watch"],
        "config_schema": [
            _field("bucket", "Bucket", "text"),
            _field("prefix", "Prefix", "text"),
        ],
    },
    {
        "connector_key": "parquet",
        "category": "对象存储与文件",
        "display_name": "Parquet",
        "runtime_family": "file-format",
        "status": "CATALOG",
        "description": "Parquet 文件、分区目录与样本读取。",
        "auth_modes": ["FILE_PATH"],
        "capabilities": ["asset_discovery", "schema_introspection", "sample_read", "stats_capture"],
        "config_schema": [_field("path", "路径", "text")],
    },
    {
        "connector_key": "csv",
        "category": "对象存储与文件",
        "display_name": "CSV",
        "runtime_family": "file-format",
        "status": "ACTIVE",
        "description": "CSV 文件与样本读取。",
        "auth_modes": ["FILE_PATH"],
        "capabilities": ["connectivity", "asset_discovery", "schema_introspection", "sample_read", "stats_capture", "change_watch"],
        "config_schema": [
            _field("path", "路径", "text", required=True, placeholder="D:\\data\\orders.csv"),
            _field("delimiter", "分隔符", "text", default=","),
            _field("encoding", "编码", "text", default="utf-8"),
            _field("has_header", "包含表头", "select", default="true"),
            _field("memory_scope_default", "默认记忆范围", "select", default="PRIVATE"),
        ],
    },
    {
        "connector_key": "kafka",
        "category": "消息与流",
        "display_name": "Kafka",
        "runtime_family": "message-log",
        "status": "ACTIVE",
        "description": "Topic、Partition、Schema Registry 与 Lag 观测。",
        "auth_modes": ["PLAINTEXT", "SASL"],
        "capabilities": ["connectivity", "instance_discovery", "asset_discovery", "stats_capture", "change_watch", "cdc_support"],
        "config_schema": [
            _field("bootstrap_servers", "Bootstrap Servers", "text", required=True, placeholder="127.0.0.1:9092"),
            _field("security_protocol", "安全协议", "text", default="PLAINTEXT"),
        ],
    },
    {
        "connector_key": "mongodb",
        "category": "NoSQL 与搜索",
        "display_name": "MongoDB",
        "runtime_family": "document-kv-search",
        "status": "ACTIVE",
        "description": "文档型数据库与集合结构发现。",
        "auth_modes": ["USERNAME_PASSWORD", "URI"],
        "capabilities": ["connectivity", "instance_discovery", "asset_discovery", "sample_read", "stats_capture", "change_watch"],
        "config_schema": [
            _field("uri", "URI", "text", required=True, placeholder="mongodb://127.0.0.1:27017"),
            _field("database", "数据库", "text"),
        ],
    },
    {
        "connector_key": "elasticsearch",
        "category": "NoSQL 与搜索",
        "display_name": "Elasticsearch / OpenSearch",
        "runtime_family": "document-kv-search",
        "status": "CATALOG",
        "description": "索引结构、映射与搜索集群指标。",
        "auth_modes": ["USERNAME_PASSWORD", "API_KEY"],
        "capabilities": ["connectivity", "asset_discovery", "schema_introspection", "stats_capture", "query_pushdown"],
        "config_schema": [_field("endpoint", "Endpoint", "text")],
    },
    {
        "connector_key": "generic-rest",
        "category": "SaaS 与 API",
        "display_name": "Generic REST API",
        "runtime_family": "saas-api",
        "status": "CATALOG",
        "description": "通用 REST 元数据接入。",
        "auth_modes": ["API_KEY", "BEARER"],
        "capabilities": ["connectivity", "asset_discovery", "stats_capture", "change_watch"],
        "config_schema": [
            _field("base_url", "Base URL", "text"),
            _field("api_key", "API Key", "password"),
        ],
    },
    {
        "connector_key": "salesforce",
        "category": "SaaS 与 API",
        "display_name": "Salesforce",
        "runtime_family": "saas-api",
        "status": "CATALOG",
        "description": "CRM 对象、字段与刷新模式发现。",
        "auth_modes": ["OAUTH", "USERNAME_PASSWORD"],
        "capabilities": ["connectivity", "asset_discovery", "schema_introspection", "stats_capture", "change_watch"],
        "config_schema": [_field("instance_url", "实例地址", "text")],
    },
    {
        "connector_key": "neo4j",
        "category": "图 / 时序 / 向量",
        "display_name": "Neo4j",
        "runtime_family": "graph-timeseries-vector",
        "status": "CATALOG",
        "description": "图数据库 schema 与关系发现。",
        "auth_modes": ["USERNAME_PASSWORD"],
        "capabilities": ["connectivity", "asset_discovery", "schema_introspection", "query_pushdown"],
        "config_schema": [_field("uri", "URI", "text")],
    },
    {
        "connector_key": "qdrant",
        "category": "图 / 时序 / 向量",
        "display_name": "Qdrant",
        "runtime_family": "graph-timeseries-vector",
        "status": "CATALOG",
        "description": "向量集合、索引与负载观测。",
        "auth_modes": ["API_KEY"],
        "capabilities": ["connectivity", "asset_discovery", "stats_capture", "query_pushdown"],
        "config_schema": [_field("url", "服务地址", "text")],
    },
]
